### ISSUE TITLE
Test faulty strings

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/NSString-HYPRelationshipParser#2]

**Comment by NSElvis** [comment]
Supporting faulty strings looks a bit dirty, not sure if we want to support it

**Comment by zenangst** [comment]
Probably better if we make it crash so that it's more obvious what's going on, what do you think?

**Comment by NSElvis** [comment]
https://github.com/hyperoslo/NSString-HYPRelationshipParser/pull/5
